# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
         npm install
         node app.js
         
         
    # Runs a set of commands using the runners shell
    - name: Send A job test To TestEngine
      run: node testengine -u jonathan -p testengine -H ec2-3-129-173-1.us-east-2.compute.amazonaws.com:8080 run project /testengine/TestEngineSchemaC-readyapi-project.xml 
     # run: echo -u "admin:testengine" --data-binary "@TestEngineSchemaC-readyapi-project.xml" -X POST "http://ec2-3-129-173-1.us-east-2.compute.amazonaws.com:8080/api/v1/testjobs?async=false"
